/* ============================================================
   PORTAL V2 — semilla_fix.sql
   Corrección post-semilla:
     - core.area    : MERGE (inserta sólo las filas faltantes)
     - cat.sistema  : INSERT (tabla vacía, falló por FK)
     - core.empleado: INSERT (tabla vacía, falló por FK)
   Ejecutar en PortalV2 después de semilla_datos.sql
   ============================================================ */

USE PortalV2;
GO

/* ============================================================
   1. core.area  — MERGE: inserta las que no existen
   ============================================================ */
SET IDENTITY_INSERT core.area ON;

MERGE core.area AS tgt
USING (VALUES
  (1,  'SUCURSAL MEXICALI',                        'MXL', 1),
  (2,  'COMPRAS',                                  'CMP', 1),
  (3,  'SUCURSAL HERMOSILLO',                      'HMO', 1),
  (4,  'SUCURSAL TIJUANA',                         'TIJ', 1),
  (5,  'SUCURSAL ENSENADA',                        'ENS', 1),
  (6,  'SUCURSAL OBREGON',                         'OBR', 1),
  (7,  'CREDITO Y COBRANZA',                       'CXC', 1),
  (8,  'MKT Y RP',                                 'MKT', 1),
  (9,  'TECNOLOGIAS',                              'TIC', 1),
  (10, 'DIRECCION GENERAL',                        'DGN', 1),
  (11, 'AUDITORIA',                                'AUD', 1),
  (12, 'CONTABILIDAD',                             'CON', 1),
  (13, 'FINANZAS',                                 'FIN', 1),
  (14, 'RECURSOS HUMANOS',                         'RRH', 1),
  (15, 'LOGISTICA',                                'LOG', 1),
  (16, 'PRODUCCION',                               'PRD', 1),
  (17, 'TESORERIA',                                'TES', 1),
  (18, 'COMERCIAL',                                'CMR', 1),
  (19, 'MANTENIMIENTO',                            'MTO', 1),
  (20, 'CALIDAD',                                  'CAL', 1),
  (21, 'OPERACIONES',                              'OPS', 1),
  (22, 'CUENTAS POR COBRAR',                       'CPC', 1),
  (23, 'COORDINADOR (A) MANTENIMIENTO',            'CMT', 0),
  (24, 'AUXILIAR ALMACEN',                         'AAL', 0),
  (25, 'COORDINADOR DE MANTENIMIENTO DE FLOTILLA', 'CMF', 0),
  (26, 'AUXILIAR PRODUCCION',                      'APD', 0),
  (27, 'JEFE (A) DE DEPARTAMENTO',                 'JDP', 0),
  (28, 'AUXILIAR LABORATORIO',                     'ALB', 0),
  (29, 'AUXILIAR DE DEPARTAMENTO',                 'ADP', 0),
  (30, 'COORDINADOR (A) PRODUCCION',               'CPD', 0),
  (31, 'ENCARGADO (A) DE ALMACEN',                 'EAL', 0),
  (32, 'LIDER MANTENIMIENTO T1',                   'LM1', 0),
  (33, 'JEFE (A) SANIDAD',                         'JSA', 0),
  (34, 'JEFE (A) CALIDAD Y DESARROLLO',            'JCD', 0),
  (35, 'AUXILIAR SUPERVISOR',                      'ASP', 0),
  (36, 'INSPECTOR (A) JR',                         'IJR', 0),
  (37, 'AUXILIAR MANTENIMIENTO T2',                'AM2', 0),
  (38, 'ANALISTA DE PRODUCCION',                   'ANA', 0),
  (39, 'AUXILIAR DOCUMENTADOR',                    'ADO', 0),
  (40, 'AUXILIAR SOPORTE',                         'AST', 0),
  (41, 'AUXILIAR MANTENIMIENTO T3',                'AM3', 0),
  (42, 'HORNOS',                                   'HOR', 1),
  (43, 'CARNES FRIAS INYECCION',                   'CFI', 1),
  (44, 'LABORATORIO',                              'LAB', 1),
  (45, 'CARNICERIA',                               'CAR', 1),
  (46, 'EMBUTIDOS MATUTINO',                       'EMM', 1),
  (47, 'MANTECA',                                  'MAN', 1),
  (48, 'ALMACEN REFRIGERADOS',                     'ALR', 1),
  (49, 'EMPAQUE',                                  'EMP', 1),
  (50, 'SANIDAD',                                  'SAN', 1),
  (51, 'CALIDAD Y DESARROLLO',                     'CYD', 1),
  (52, 'REFACCIONES',                              'REF', 1),
  (53, 'EMBUTIDOS VESPERTINO',                     'EMV', 1),
  (54, 'DOCUMENTACION',                            'DOC', 1)
) AS src (ID_Area, Nombre, Serie, Activo)
ON tgt.ID_Area = src.ID_Area
WHEN NOT MATCHED BY TARGET THEN
  INSERT (ID_Area, Nombre, Serie, Activo)
  VALUES (src.ID_Area, src.Nombre, src.Serie, src.Activo);

SET IDENTITY_INSERT core.area OFF;
GO

/* ============================================================
   2. cat.sistema  (sin filas previas — falló completo por FK)
   ============================================================ */
SET IDENTITY_INSERT cat.sistema ON;
INSERT INTO cat.sistema (ID_Sistema, ID_Area, Nombre, Descripcion, Activo) VALUES
(1,  9, 'SAP',               'Sistema ERP (SAP)',                             1),
(2,  9, 'App Calidad',        'Aplicación de calidad',                        1),
(3,  9, 'App Móvil',          'Aplicación o portal de ventas',                1),
(4,  9, 'Red',                'Conexión de red e interrupciones',             1),
(5,  9, 'Equipo de Cómputo',  'Periféricos, hardware y software',             1),
(6,  9, 'TRESS',              'Sistema de nómina',                            1),
(7,  9, 'Office',             'Aplicaciones de oficina (Word, Excel, etc.)',  1),
(8,  9, 'Otros',              'Cualquier otro sistema',                       1),
(9,  9, 'CCTV',               'Problemas relacionados con CCTV',              1),
(10, 9, 'Sistema de gestion', 'Portal de incidencias de tecnologias',         1),
(11, 9, 'Dashboard',          'Portal de indicadores operativos',             1),
(12, 9, 'Prueba',             NULL,                                           0),
(13, 9, 'Suministro eléctrico','',                                            1),
(14, 9, 'APP',                'Programas que se instalan en equipo.',         1);
SET IDENTITY_INSERT cat.sistema OFF;
GO

/* ============================================================
   3. core.empleado  (sin filas previas — falló completo por FK)
   ============================================================ */
INSERT INTO core.empleado
    (Numero_Empleado, Nombre, Correo, Extension, Telefono,
     UsuarioAnyDesk, ClaveAnyDesk, ID_Sucursal, ID_Puesto, ID_Area, Activo)
VALUES
(11,   'CATALINA ORTEGA MUÑOZ',                  NULL,                                            NULL,   NULL, NULL, NULL, 8,  65, 16, 1),
(12,   'LUIS JAVIER FIMBRES ASTIAZARAN',         'luisfa@empacadorarosarito.com',                 NULL,   NULL, NULL, NULL, 2,  33, 10, 1),
(16,   'MARIA IVONE FIMBRES ASTIAZARAN',         NULL,                                            NULL,   NULL, NULL, NULL, 2,   8, 10, 1),
(18,   'ANSELMO SOLIS MARTINEZ',                 NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 42, 1),
(19,   'JUAN MANUEL GRANADOS CARRILLO',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 43, 1),
(27,   'PAULO MENDEZ AGUILAR',                   NULL,                                            NULL,   NULL, NULL, NULL, 2,  63,  2, 1),
(28,   'MA HILDA HERNANDEZ RODRIGUEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  67, 44, 1),
(38,   'HECTOR IVAN SALCEDO HERNANDEZ',          'i.salcedo@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 2,  44,  2, 1),
(42,   'ALVARO GARCIA MURILLO',                  NULL,                                            NULL,   NULL, NULL, NULL, 2,  14, 12, 1),
(48,   'VERONICA CRUZ MILLAN',                   'v.cruz@empacadorarosarito.com.mx',              NULL,   NULL, NULL, NULL, 2,  29, 17, 1),
(53,   'JORGE MONTES PEREZ',                     NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 45, 1),
(72,   'ANTONIO NELSON ACOSTA HIGUERA',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 46, 1),
(89,   'MARIA TERESA BASTIDAS BURGOS',           't.bastidas@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 2,  51, 17, 1),
(94,   'ROGELIO ISAIAS JIMENEZ PEREZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 45, 1),
(97,   'JORGE DOMINGO ZATARAIN BALDENEGRO',      NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 47, 1),
(100,  'GERARDO GOMEZ MOLINA',                   NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(104,  'MARIA DEL ROSARIO RIOS VILLALOBOS',      'r.rios@empacadorarosarito.com.mx',              NULL,   NULL, NULL, NULL, 8,  48, 16, 1),
(106,  'ALMA LUZ ESPARZA AGUAYO',                NULL,                                            NULL,   NULL, NULL, NULL, 8,  69, 16, 1),
(135,  'HILDA IRENE GARCIA RIVAS',               'h.garcia@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,  10, 11, 1),
(141,  'JERARDO CARRILLO CAMPOZ',                NULL,                                            NULL,   NULL, NULL, NULL, 2,  23,  7, 1),
(155,  'BERNARDINO PEREZ CERVANTES',             NULL,                                            NULL,   NULL, NULL, NULL, 8,  70, 48, 1),
(171,  'SERGIO OSUNA OSUNA',                     NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 42, 1),
(314,  'LIDIA RAMIREZ PARRA',                    'l.ramirez@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 6,  26,  6, 1),
(447,  'MIGUEL ANGEL RAMIREZ RODRIGUEZ',         NULL,                                            NULL,   NULL, NULL, NULL, 8,  63, 48, 1),
(457,  'MARIO JESUS ESCOBEDO FIMBRES',           'm.escobedo@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 7,  38, 10, 1),
(539,  'ROSA ARMIDA LOPEZ DIAZ',                 'r.lopez@empacdorarosarito.com.mx',              NULL,   NULL, NULL, NULL, 1,  40,  1, 1),
(640,  'JONATHAN MARQUEZ ROSALES',               NULL,                                            NULL,   NULL, NULL, NULL, 8,  71, 19, 1),
(667,  'CARINA ADRIANA CHAPARRO GONZALEZ',       'aux.reclutamiento@empacadorarosarito.com.mx',   NULL,   NULL, NULL, NULL, 2,  35, 14, 1),
(687,  'MAYRA MIRANDA RIOS',                     NULL,                                            NULL,   NULL, NULL, NULL, 3,  52,  3, 1),
(1054, 'HECTOR MANUEL RODRIGUEZ MORONES',        'h.rodriguez@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 7,  37, 10, 1),
(1100, 'ALMA PATRICIA LOPEZ BURGOS',             'a.lopez@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,  36, 10, 1),
(1214, 'ISRAEL ARMANDO AGUILAR LICEA',           'i.aguilar@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 7,  45, 15, 1),
(1232, 'CRISTINA SAUCEDO RAMIREZ',               'c.saucedo@empacadorarosarito.com.mx',           '1142', NULL, NULL, NULL, 2,  25, 12, 1),
(1263, 'JOSE ALFREDO ZAMORA BENITES',            NULL,                                            NULL,   NULL, NULL, NULL, 8,  70, 16, 1),
(1410, 'JOSE ALFREDO VAZQUEZ LOPEZ',             NULL,                                            NULL,   NULL, NULL, NULL, 1,  53,  1, 1),
(1479, 'MARCIA CRISTINA FIMBRES ASTIAZARAN',     'm.fimbres@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 2,  54, 17, 1),
(1642, 'JOEL LEONEL GARCIA GARCIA',              'j.garcia@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,   9, 11, 1),
(1662, 'MARCELA JIMENEZ REGALADO',               NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 49, 1),
(1716, 'KARLA EVELYN NUÑEZ PLANCARTE',           'k.nunez@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,  28, 14, 1),
(1730, 'YESMIN ROCIO BERNAL ROMERO',             'r.bernal@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,  24, 12, 1),
(1837, 'LUIS ALBERTO FIMBRES VILLASEÑOR',        'l.fimbres@empacadorarosarito.com.mx',           '1125', NULL, NULL, NULL, 8,  58, 10, 1),
(1849, 'JOSE ALFREDO MUNGUIA VALENZUELA',        NULL,                                            NULL,   NULL, NULL, NULL, 3,  53,  3, 0),
(1864, 'RAFAEL ERNESTO BARRERA BERNAL',          'apt.her@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 3,   2,  3, 1),
(1945, 'ANAYELI MONTAÑO FLORES',                 'cxc.hermosillo@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 3,  26,  3, 1),
(1951, 'JESUS ALBERTO LEYVA MARTINEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 3,  40,  3, 0),
(2081, 'KARIM ARMANDO SOTO CARRILLO',            'a.soto@empacadorarosarito.com.mx',              '1131', NULL, NULL, NULL, 8,  60, 19, 1),
(2105, 'FRANCISCO GILBERTO VALENZUELA MORENO',   NULL,                                            NULL,   NULL, NULL, NULL, 6,  63,  6, 1),
(2189, 'JESUS RAMON MURILLO AYON',               NULL,                                            NULL,   NULL, NULL, NULL, 8,  72, 50, 1),
(2242, 'ADALBERTO JIMENEZ TORRUCO',              'a.jimenez@empacadorarosarito.com.mx',           '1138', NULL, NULL, NULL, 8,  55, 19, 1),
(2321, 'HUGO DIAZ',                              NULL,                                            NULL,   NULL, NULL, NULL, 8,  63, 48, 1),
(2373, 'JORGE LUIS BORRAYO ROSAS',               NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 46, 1),
(2376, 'CYNTHIA LUCIA ROMERO JIMENEZ',           'enfermeria@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 2,  34, 14, 1),
(2515, 'VICTOR GONZALEZ GONZALEZ',               NULL,                                            NULL,   NULL, NULL, NULL, 1,  53,  1, 1),
(2575, 'IRIS VANESSA LANGARICA MARTINEZ',        'v.langarica@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 8,  46, 16, 1),
(2622, 'JOSE ENRIQUE MURRIETA DELGADO',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 43, 1),
(2623, 'JUANA LIZBETH MURRIETA DELGADO',         'a.costos@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,  14, 12, 1),
(2720, 'BRIANDA DIANEY MARTINEZ PONCE',          'cxc.mexicali@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 1,  11,  1, 1),
(2754, 'NORMAN JONATHAN VALENCIA TAPIA',         NULL,                                            NULL,   NULL, NULL, NULL, 8,  73, 51, 1),
(2781, 'LUIS ALBERTO RODRIGUEZ PAEZ',            'l.rodriguez@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 6,  41,  6, 1),
(2784, 'LORENA JIMENEZ CORRAL',                  'l.jimenez@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 3,  41,  3, 1),
(2793, 'EDGAR HERIBERTO BENAVIDES SALAZAR',      NULL,                                            NULL,   NULL, NULL, NULL, 4,  53,  4, 1),
(2874, 'RAFAEL MANUEL PINEDA MARSHALL',          'r.pineda@empacadorarosarito.com.mx',            '1122', NULL, NULL, NULL, 8,  51, 19, 1),
(2924, 'DIANA JUDITH OSUNA SANTIAGO',            'documentacion@empacadorarosarito.com.mx',       '1141', NULL, NULL, NULL, 8,  56, 20, 1),
(2953, 'SAMUEL MEJIA CHACON',                    's.mejia@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,  12,  2, 1),
(3134, 'JUAN MARTIN HUIZAR VILLANUEVA',          NULL,                                            NULL,   NULL, NULL, NULL, 3,  52,  3, 1),
(3240, 'GRECIA MAGDALENA VILLA CONTRERAS',       NULL,                                            NULL,   NULL, NULL, NULL, 3,  18,  3, 0),
(3257, 'SILVIA VALENZUELA ENCINAS',              'pv.obregon@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 6,  20,  6, 1),
(3258, 'RUBEN NOE SANCHEZ',                      'apt.ensenada@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 5,   3,  5, 1),
(3319, 'RAFAEL DANIEL MUÑOZ CONTRERAS',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  63, 52, 1),
(3400, 'SERGIO ANDREY MONTES HERNANDEZ',         NULL,                                            NULL,   NULL, NULL, NULL, 5,  53,  5, 1),
(3401, 'CARLOS MANUEL FUENTES GOMEZ',            NULL,                                            NULL,   NULL, NULL, NULL, 5,  53,  5, 1),
(3428, 'CLAUDIA DIAZ GALLEGOS',                  'cxc.ensenada@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 5,  11,  5, 1),
(3504, 'STEPHANY LIZETH RIVAS VALLE',            'pv.tijuana@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 4,  20,  4, 1),
(3572, 'MIRIAN NOEMI LUA MAGALLANES',            'c.mexicali@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 1,  19,  1, 1),
(3578, 'JULIO CESAR LOPEZ MAC GREW',             NULL,                                            NULL,   NULL, NULL, NULL, 3,  53,  3, 1),
(3620, 'DAVID MONTES DIAZ',                      NULL,                                            NULL,   NULL, NULL, NULL, 7,  63, 15, 1),
(3657, 'YESENIA BORBON APODACA',                 NULL,                                            NULL,   NULL, NULL, NULL, 1,  52,  1, 0),
(3740, 'RICARDO VILLALVAZO FALCON',              'r.villalvazo@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 5,  40,  5, 1),
(3806, 'FABIOLA CHAVEZ URREA',                   'f.chavez@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 6,  35,  6, 1),
(3884, 'EDWARD ANTONIO RANGEL LANDINO',          'e.rangel@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 7,  31, 18, 1),
(3925, 'JESUS EDUARDO VILLEGAS ARMENTA',         'j.villegas@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 2,  13, 12, 1),
(3927, 'YOLANDA MERAZ MERAZ',                    NULL,                                            NULL,   NULL, NULL, NULL, 4,  52,  4, 1),
(3935, 'MARIA INES GOMEZ LEON',                  'pv.mexicali@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 1,  20,  1, 1),
(3958, 'FRANCIA NISSAN GALLEGOS HUITRON',        'c.ensenada@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 5,  19,  5, 1),
(4049, 'KAREN SHANTELL BAYLISS GONZALEZ',        NULL,                                            NULL,   NULL, NULL, NULL, 4,  19,  4, 0),
(4075, 'AZUCENA CORONADO CRUZ',                  'rh.hermosillo@empacadorarosarito.com.mx',       NULL,   NULL, NULL, NULL, 3,  35,  3, 1),
(4159, 'HUGO IVAN BARBA SORIA',                  NULL,                                            NULL,   NULL, NULL, NULL, 8,  35, 16, 1),
(4263, 'MICHELLE DESIRE CARMONA ALBARRAN',       'rh.ensenada@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 5,  35,  5, 1),
(4389, 'MARIA ALEJANDRA ACEVEDO AMADOR',         'e.calidad@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 5,  20,  5, 1),
(4441, 'KEILA ROCHA TAGLE',                      'k.rocha@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,  30, 13, 1),
(4517, 'OSCAR ALEJANDRO RUELAS OBESO',           NULL,                                            NULL,   NULL, NULL, NULL, 7,  63, 15, 1),
(4525, 'GERARDO ALONSO SEGOVIANO SANCHEZ',       NULL,                                            NULL,   NULL, NULL, NULL, 4,  53,  4, 1),
(4558, 'HUMBERTO ROJAS GERONIMO',                NULL,                                            NULL,   NULL, NULL, NULL, 8,  21, 16, 0),
(4559, 'ALEJANDRA ELISA CASTRO MURILLO',         NULL,                                            NULL,   NULL, NULL, NULL, 6,  19,  6, 0),
(4562, 'RAUL RICARDO GARCIA DAVALOS',            NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 42, 1),
(4578, 'MANUEL DIAZ MENDEZ',                     'm.diaz@empacadorarosarito.com.mx',              NULL,   NULL, NULL, NULL, 2,  50,  9, 1),
(4638, 'JAQUELINE LOPEZ RAMIREZ',                NULL,                                            NULL,   NULL, NULL, NULL, 8,  67, 44, 1),
(4663, 'SAUL ADRIAN GALAVIZ GARCIA',             NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(4676, 'EMILIO ZAMORA TORRES',                   'e.zamora@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,   7,  9, 1),
(4692, 'ITZEL CUADRAS GAXIOLA',                  NULL,                                            '1136', NULL, NULL, NULL, 8,  59, 20, 1),
(4744, 'JORGE ALEXIS FREGOSO RUIZ',              NULL,                                            NULL,   NULL, NULL, NULL, 4,  41,  4, 1),
(4758, 'JOSE LUIS RODRIGUEZ FLORES',             NULL,                                            NULL,   NULL, NULL, NULL, 8,  74, 50, 1),
(4766, 'GLADIS ADRIANA GARCIA VALENZUELA',       'supervisor.her@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 3,  52,  3, 1),
(4828, 'ULISES AGUSTIN ZAMORA BAÑUELOS',         NULL,                                            NULL,   NULL, NULL, NULL, 8,  67, 44, 1),
(4840, 'JUAN CARLOS GARCIA HERNANDEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(4871, 'SERGIO CATAÑO GOMEZ',                    NULL,                                            NULL,   NULL, NULL, NULL, 2,  63,  2, 1),
(4873, 'RAFAEL SALDIVAR CARRILLO',               NULL,                                            NULL,   NULL, NULL, NULL, 4,  63,  4, 1),
(4894, 'MARCO ANTONIO PATRON SAUCEDA',           NULL,                                            NULL,   NULL, NULL, NULL, 2,  16, 13, 1),
(4904, 'NOHEMI GUADALUPE GUTIERREZ GARCIA',      'c.hermosillo@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 3,  19,  3, 1),
(4921, 'NORA GUADALUPE TORRES ONTIVEROS',        'pv.hermosillo@empacadorarosarito.com.mx',       NULL,   NULL, NULL, NULL, 3,  20,  3, 1),
(4922, 'MARIA DEL CARMEN TRAVANINO MEJIA',       'm.travanino@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 2,  49, 14, 1),
(4946, 'FRANCISCO ANTONIO OLIVAS MARTINEZ',      NULL,                                            NULL,   NULL, NULL, NULL, 3,  53,  3, 0),
(4975, 'YESENIA MARQUEZ ARADILLAS',              'y.marquez@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 2,  27, 14, 1),
(4981, 'ROBERTO MENDOZA TRUJILLO',               'r.mendoza@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 7,  32,  8, 1),
(5026, 'MAYRA IRASEMA PARTIDA LOZANO',           'c3.hermosillo@empacadorarosarito.com.mx',       NULL,   NULL, NULL, NULL, 3,  11,  3, 1),
(5039, 'LARISSA RIVERA RODRIGUEZ',               NULL,                                            NULL,   NULL, NULL, NULL, 2,   4,  7, 0),
(5041, 'VIANEY RODRIGUEZ GARCIA',                NULL,                                            NULL,   NULL, NULL, NULL, 4,  19,  4, 0),
(5064, 'MIRIAM NAYE JIMENEZ MADERO',             NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5072, 'DIEGO ANTONIO MORALES CATALAN',          'auxss@empacadorarosarito.com.mx',               NULL,   NULL, NULL, NULL, 2,  17, 14, 1),
(5080, 'ABIGAIL CASTAÑEDA MARTINEZ',             'rh.mexicali@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 1,  35,  1, 1),
(5088, 'GUILLERMO SUSUNAGA RODRIGUEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5095, 'DALAI ESPINOZA GUTIERREZ',               'inspeccion@empacadorarosarito.com.mx',          '1136', NULL, NULL, NULL, 8,  59, 20, 1),
(5119, 'FRANCISCO RODRIGUEZ SALAZAR',            'almacenplantasecos@empacadorarosarito.com.mx',  NULL,   NULL, NULL, NULL, 2,   2,  2, 1),
(5120, 'JESUS BENJAMIN BORQUEZ VERDUGO',         'apt.obregon@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 6,   3,  6, 1),
(5121, 'JOSE LUIS GUDIÑO PICHARDO',              NULL,                                            NULL,   NULL, NULL, NULL, 6,  53,  6, 1),
(5126, 'JESUS GIOVANNI SILVA MORALES',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 53, 1),
(5129, 'JOSE GILBERTO BELTRAN CRUZ',             NULL,                                            NULL,   NULL, NULL, NULL, 8,  76, 19, 1),
(5133, 'MARIA DE JESUS GARCIA RAMIREZ',          'ca1.produccion@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 8,  22, 16, 1),
(5152, 'LAZARO CORNEJO SANCHEZ',                 'a.procedimientos@empacadorarosarito.com.mx',    NULL,   NULL, NULL, NULL, 2,  16, 13, 1),
(5182, 'MARCELA LORELEY ESQUIVEL GONZALEZ',      'supervisor.mex@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 1,  52,  1, 1),
(5183, 'ERIKA ALEJANDRA FLORES MONTERO',         NULL,                                            NULL,   NULL, NULL, NULL, 4,  52,  4, 1),
(5189, 'NAYDA DEL CARMEN ROQUE CARRILLO',        'a.nomina@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 2,  35, 14, 1),
(5196, 'ULISES ADALBERTO SAUCEDA LOPEZ',         'reclutamiento@empacadorarosarito.com.mx',       NULL,   NULL, NULL, NULL, 2,  35, 14, 1),
(5217, 'MANUEL ENRIQUE ARGUELLES IBARRA',        NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(5218, 'EDUARDO JIMENEZ MENDEZ',                 NULL,                                            NULL,   NULL, NULL, NULL, 1,  63,  1, 1),
(5225, 'IVER GEOVANNY VELAZCO ARMENDARIZ',       NULL,                                            NULL,   NULL, NULL, NULL, 4,   2,  4, 0),
(5230, 'DANIEL ALEJANDRO SALAS MONTOYA',         NULL,                                            NULL,   NULL, NULL, NULL, 4,  21,  4, 1),
(5237, 'ARIANA CASTAÑEDA DEL CASTILLO',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5255, 'AIDA ARACELI OCHOA MARTINEZ',            'a.ochoa@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,  39, 10, 1),
(5270, 'ANGEL ADOLFO ACUÑA MARTINEZ',            'apt.mexicali@empacadorarosarito.com.mx',        NULL,   NULL, NULL, NULL, 1,   1,  1, 1),
(5290, 'JOSE JESUS GARCIA LEYVA',                NULL,                                            NULL,   NULL, NULL, NULL, 6,  63,  6, 1),
(5300, 'MACARIO PEREZ VENTURA',                  NULL,                                            NULL,   NULL, NULL, NULL, 8,  68, 47, 1),
(5312, 'MIGUEL RODRIGUEZ BORBON',                NULL,                                            NULL,   NULL, NULL, NULL, 6,  53,  6, 1),
(5316, 'JOAHNNA MICHELLE PEREZ CASTILLO',        'a.contable@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 2,  13, 12, 1),
(5341, 'JUAN DANIEL GOMEZ HERRERA',              NULL,                                            NULL,   NULL, NULL, NULL, 5,  63,  5, 1),
(5343, 'MARIA ELENA RODRIGUEZ DAVILA',           'e.rodriguez@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 2,  42, 14, 1),
(5346, 'EDGAR ANTONIO GOMEZ LOPEZ',              'e.gomez@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 2,   6,  9, 1),
(5347, 'MARIA FERNANDA DE LA CRUZ PERALTA',      NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5348, 'MARIA FERNANDA LOPEZ VAZQUEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  77, 16, 1),
(5351, 'HECTOR NARCISO MERCADO FLORES',          NULL,                                            NULL,   NULL, NULL, NULL, 4,  52,  4, 1),
(5353, 'MARIA GUADALUPE PADILLA BORQUEZ',        NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5373, 'ALEJANDRO DELGADO CARDENAS',             NULL,                                            NULL,   NULL, NULL, NULL, 4,  40,  4, 0),
(5407, 'EMANUEL SERGIO BARTOLON MUÑOZ',          'cd.calidad@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 4,  41,  4, 1),
(5411, 'MANUEL IGNACIO COTA BLAKE',              'supervisor.ens@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 5,  52,  5, 1),
(5419, 'LIZBETH GAMA VELAZQUEZ',                 NULL,                                            NULL,   NULL, NULL, NULL, 8,  78, 54, 1),
(5426, 'CARLOS EDUARDO LOPEZ ENCINAS',           'c.lopez@empacadorarosarito.com.mx',             NULL,   NULL, NULL, NULL, 6,  40,  6, 1),
(5439, 'JOSE GERARDO CASAS ARMENTA',             NULL,                                            NULL,   NULL, NULL, NULL, 2,  63,  2, 1),
(5444, 'IVAN DE JESUS SANCHEZ OLIVAS',           NULL,                                            NULL,   NULL, NULL, NULL, 1,  63,  1, 1),
(5488, 'MARCO ANTONIO QUEZADA GARCIA',           NULL,                                            NULL,   NULL, NULL, NULL, 4,  63,  4, 1),
(5502, 'OSCAR ALEJANDRO FIMBRES TORRES',         NULL,                                            NULL,   NULL, NULL, NULL, 4,  52,  4, 1),
(5504, 'JOSE OSWALDO CAMPOY ORTIZ',              'supervisor.obr@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 6,  53,  6, 1),
(5527, 'BRIAN DANIEL ASTUDILLO BELTRAN',         NULL,                                            NULL,   NULL, NULL, NULL, 8,  21, 16, 1),
(5530, 'JOHANA PATRICIA CHAPARRO GONZALEZ',      'pv.alamos@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 4,  20,  4, 1),
(5534, 'JOSUE RODOLFO LOPEZ ZAMARRIPA',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  79, 16, 1),
(5537, 'ANGEL ROBERTO FLORES DURAZO',            'a.flores@empacadorarosarito.com.mx',            NULL,   NULL, NULL, NULL, 7,   5,  8, 1),
(5551, 'DIANA CRISTINA FLORES AMORES',           'ca2.produccion@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 8,  22, 16, 1),
(5555, 'CRISTINA LIZBETH PARRA VENTURA',         'calidadmexicali@empacadorarosarito.com.mx',     NULL,   NULL, NULL, NULL, 1,  41,  1, 1),
(5559, 'RICARDO DE LA TRINIDAD FELIX',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5567, 'ZINDY LISSETTE DELFIN HERNANDEZ',        'cd.tijuana@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 7,  21, 15, 1),
(5575, 'MARTIN ELEAZAR AYALA IBARRA',            NULL,                                            NULL,   NULL, NULL, NULL, 8,  66, 53, 1),
(5594, 'RICARDO ARCADIO HERNANDEZ LUNA',         'laboratorio@empacadorarosarito.com.mx',         '1126', NULL, NULL, NULL, 8,  61, 20, 1),
(5601, 'MARISELA AMADOR GODINEZ',                'marisela.a@empacadorarosarito.com.mx',          NULL,   NULL, NULL, NULL, 2,  43,  7, 1),
(5607, 'ARTURO NIETO ESTRADA',                   NULL,                                            NULL,   NULL, NULL, NULL, 8,  63, 52, 1),
(5612, 'MIGUEL ANGEL ACOSTA RODRIGUEZ',          'supervisor.tij@empacadorarosarito.com.mx',      NULL,   NULL, NULL, NULL, 4,  52,  4, 1),
(5636, 'MIRIAM SANCHEZ RIVERA',                  'adm.tijuana@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 2,   4,  7, 1),
(5637, 'KARINA BERENICE RODRIGUEZ CABALLERO',    NULL,                                            NULL,   NULL, NULL, NULL, 4,  11, 22, 0),
(5641, 'ZADYURY ARIADNA CASTAÑEDA BARRAZA',      NULL,                                            NULL,   NULL, NULL, NULL, 5,  20,  5, 0),
(5642, 'GUSTAVO MANGOL GONZALEZ',                NULL,                                            NULL,   NULL, NULL, NULL, 4,  52,  4, 0),
(5646, 'JONATHAN CASTRO CHAVEZ',                 NULL,                                            NULL,   NULL, NULL, NULL, 2,  15, 12, 0),
(5651, 'JESSICA ANAHI NORIEGA YOC',              NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5660, 'EDGAR RICARDO GOMEZ LEDESMA',            NULL,                                            NULL,   NULL, NULL, NULL, 1,  52,  1, 0),
(5661, 'MONICA RAMIREZ NAVARRO',                 'm.ramirez@empacadorarosarito.com.mx',           NULL,   NULL, NULL, NULL, 2,  47, 14, 1),
(5667, 'KARLA ANABEL PEÑA ZEPEDA',               NULL,                                            NULL,   NULL, NULL, NULL, 1,  52,  1, 1),
(5669, 'ANGELICA MARIA GOMEZ MUÑIZ',             NULL,                                            NULL,   NULL, NULL, NULL, 4,  35,  4, 1),
(5671, 'JOSE RAMON VELAZQUEZ ANGUIANO',          NULL,                                            NULL,   NULL, NULL, NULL, 2,  63,  2, 1),
(5684, 'SERGIO NOE RODRIGUEZ SANCHEZ',           NULL,                                            NULL,   NULL, NULL, NULL, 8,  63, 16, 1),
(5692, 'NOEMI GUADALUPE TORRES ESCOBAR',         NULL,                                            NULL,   NULL, NULL, NULL, 2,  15, 12, 1),
(5697, 'LUIS RODRIGO RAMOS LUNA',                NULL,                                            NULL,   NULL, NULL, NULL, 2,  15, 12, 1),
(5703, 'MARIA ELENA ESTRADA FELIX',              NULL,                                            NULL,   NULL, NULL, NULL, 1,  52,  1, 1),
(5715, 'BLANCA JUDITH CHAVARRIA SOTELO',         'C.OBREGON@EMPACADORAROSARITO.COM.MX',           NULL,   NULL, NULL, NULL, 6,  19,  6, 1),
(5721, 'RICARDO GERARDO FLORES PICO',            NULL,                                            NULL,   NULL, NULL, NULL, 6,  53,  6, 1),
(5754, 'LEOBARDO BRACAMONTES MARTINEZ',          NULL,                                            NULL,   NULL, NULL, NULL, 4,  63,  4, 1),
(5761, 'GERARDO MCDONAUGH MURA',                 NULL,                                            NULL,   '6642572541', NULL, NULL, 4, 40, 4, 0),
(5768, 'LLOICE GUTIERREZ AMARILLAS',             'pv.ensenada@empacadorarosarito.com.mx',         NULL,   NULL, NULL, NULL, 5,  20,  5, 1),
(5772, 'SAUL ROJAS BEAVEN',                      NULL,                                            NULL,   NULL, NULL, NULL, 8,  80, 19, 1),
(5781, 'NAYELI GANTES RIVERO',                   NULL,                                            NULL,   NULL, NULL, NULL, 2,  18, 22, 1),
(5783, 'VICTOR MANUEL PACHECO CARRILLO',         NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(5786, 'HUGO ALBERTO AHUMADA JUAREZ',            NULL,                                            NULL,   NULL, NULL, NULL, 4,  40,  4, 0),
(5792, 'LUIS ARTURO GUTIERREZ HERNANDEZ',        NULL,                                            NULL,   NULL, NULL, NULL, 2,  14, 12, 1),
(5798, 'DIEGO ARTURO RIVERA GOMEZ',              NULL,                                            NULL,   NULL, NULL, NULL, 5,  63,  5, 1),
(5803, 'KEVIN EDUARDO HERRERA DE LA CRUZ',       NULL,                                            NULL,   NULL, NULL, NULL, 8,  67, 44, 1),
(5816, 'SUSEL EILEEN RAMIREZ ZATARAIN',          NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1),
(5821, 'MARTHA LIZETH QUIÑONEZ MARTINEZ',        NULL,                                            NULL,   NULL, NULL, NULL, 8,  22, 16, 1),
(5822, 'LUIS AGUSTIN CRUZ RAMIREZ',              NULL,                                            NULL,   NULL, NULL, NULL, 4,  63,  4, 1),
(5828, 'QUEMICH AARON CONTRERAS SEGOVIA',        NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(5831, 'CLAUDIA BARRIOS RAMIREZ',                NULL,                                            NULL,   NULL, NULL, NULL, 4,  19,  4, 1),
(5834, 'MIGUEL ANGEL ESTRADA MATA',              NULL,                                            NULL,   NULL, NULL, NULL, 3,  63,  3, 1),
(5839, 'FELIX HUMBERTO ARRIAGA RAYAS',           NULL,                                            NULL,   NULL, NULL, NULL, 4,   2,  4, 1),
(5841, 'VERONICA TEQUIHUATLE TLEHUATLE',         NULL,                                            NULL,   NULL, NULL, NULL, 4,  19,  4, 1),
(5842, 'YURIRIA ALEJANDRA VELAZQUEZ DEL RAZO',   NULL,                                            NULL,   NULL, NULL, NULL, 4,  26,  4, 1),
(5843, 'ELVIX JAIR GONZALEZ RAMOS',              NULL,                                            NULL,   NULL, NULL, NULL, 8,  79, 16, 1),
(5845, 'FERNANDO DELGADO CHAVEZ',                NULL,                                            NULL,   NULL, NULL, NULL, 1,  19,  1, 1),
(5846, 'JOSE GUADALUPE VEGA MORALES',            NULL,                                            NULL,   NULL, NULL, NULL, 4,  63,  4, 1),
(5849, 'CARLOS GABRIEL MEDINA GALVAN',           NULL,                                            NULL,   NULL, NULL, NULL, 7,  64, 18, 1),
(5852, 'ITZEL CRUZ RODRIGUEZ',                   NULL,                                            NULL,   NULL, NULL, NULL, 8,  75, 51, 1);
GO

PRINT 'Fix de semilla aplicado correctamente.';
GO
